import type { Metadata } from "next";
import { Geist, Geist_Mono, Gasoek_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Image from "next/image";
import { coord } from "@/utils/constant";
import { Earth } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const gasoekOne = Gasoek_One({
  variable: "--font-gasoek-one",
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Travel Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${gasoekOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col pt-24 bg-brand-light-blue lg:overflow-hidden lg:flex-row">
        {/* Left column: header + intro section. Fixed on large screens, normal flow on small */}
        <aside className="w-full lg:fixed lg:left-0 lg:top-0 lg:w-1/3 lg:overflow-visible lg:bg-transparent lg:flex lg:flex-col lg:justify-center lg:items-center lg:mt-10">
          <header className="w-full ">
            {/* Floating (small screens) */}
            {/* Static (large screens) - fits inside left column */}
            <div className="fixed top-6 left-1/2 transform -translate-x-1/2 z-50 w-max lg:left-[16.666%] lg:transform lg:-translate-x-1/2">
              <div className="backdrop-blur-md border border-[rgba(0,0,0,0.06)] shadow-lg rounded-3xl py-2 bg-white px-4">
                <Navbar/>
              </div>
            </div>
          </header>

          <section className="w-full flex items-center justify-center mt-12 flex-col gap-6 lg:px-6 lg:pt-6">
            <div className="flex flex-col items-center text-center  ">
              <h3 className="text-7xl font-extrabold text-brand-blue font-heading">
                The Roam Report
              </h3>
              <Image
                src="/train.png"
                alt="train"
                width={100}
                height={100}
                className="my-6"
              />
              <p className="text-brand-blue text-2xl ">
                Stories and photos of long walks,
                <br /> wrong turns, and everyday discoveries
              </p>
            </div>
            <div className="w-full marquee mt-20 lg:mt-6">
              <div className="marquee-track animate-marquee">
                {[0, 1, 2].map((repeat) =>
                  coord.map((item, index) => (
                    <div
                      className="marquee-item text-brand-blue"
                      key={`m${repeat}-${index}`}
                    >
                      {item} <Earth />
                    </div>
                  )),
                )}
              </div>
            </div>
          </section>
        </aside>

        {/* Right column: main content. Scrollable on large screens */}
        <main className="w-full lg:ml-[33.333%] lg:w-[66.666%] lg:h-screen lg:overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
